// TODO: Include packages needed for this application
//these required the dependencies that were installed into this js
const inquirer = require('inquirer');
const fs = require('fs');
const generateMarkdown = require('./utils/generateMarkdown');

// Create an array of questions for user input
// ToDo: come back and uncomment things
const questions = [
  {
    type: 'input',
    message: 'What is your GitHub username?',
    name: 'github',
  },
  {
    type: 'input',
    message: 'What is your email address?',
    name: 'email',
  },
  {
    type: 'input',
    message: 'What is your projects name?',
    name: 'title',
  },
  {
    type: 'input',
    message: 'Please write a short description of your project.',
    name: 'description',
  },
  {
    type: 'list',
    message: 'What kind of license should your project have?',
    name: 'license',
    choices: ['MIT', 'IBM', 'Apache'],
  },
  {
    type: 'input',
    message: 'What command should be run to install dependencies?',
    name: 'install',
    default: 'npm i',
  },
  {
    type: 'input',
    message: 'What command should be run to run tests?',
    name: 'test',
  },
  {
    type: 'input',
    message: 'What does the user need to know about using the repo?',
    name: 'usage',
  },
  {
    type: 'input',
    message: 'What does the user need to know about contributing to the repo?',
    name: 'contribute',
  },
];

// TODO: Create a function to write README file
function writeToFile(response) {
  return fs.writeFile('README.md', response, (err) => {
    err ? console.log(err) : console.log('File was written!');
  });
}

// TODO: Create a function to initialize app
function init() {
  inquirer.prompt(questions).then((response) => {
    writeToFile(generateMarkdown(response));
  });
}

// Function call to initialize app
init();

//
//
//
//things to use:
//after class session Wednesday at 2:25
//section 14, session Tuesday at 2:22-2:30

//in working file, open comand prompt and npm install in the file
//that has your json file package.json
// will then generate a README

//will need
//to screen redord the functionality for a video clip. Use Screenify.
//to generate a sample README.md file generated by application
//as part of final turn in

//tech used - inquirer, fs, js
//

// # Table of Contents
// [Description](#description)
// [Installation](#installation)
// [Usage](#usage)
// [Contributing](#contributing)
// [Tests](#tests)
// [Questions](#questions)
// ${data.license != "" ? `[${data.license}](#license)  ` : ""}
